version: '3'

services:
  go-app:
    build:
      context: go-simple-app
      dockerfile: Dockerfile
    image: go-simple-app
    ports:
      - "8080:8080"
    networks:
      - app-network

  py-app:
    build:
      context: py-simple-app
      dockerfile: Dockerfile
    image: py-simple-app
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - URL_RUPIAH_RATE=http://free.currconv.com/api/v7/convert?q=IDR_USD&compact=ultra&apiKey=8185373ea92ce6379207
      - INTERVAL_RUPIAH_RATE=1000
      - URL_RESOURCES=https://stein.efishery.com/v1/storages/5e1edf521073e315924ceab4/list
      - URL_AUTH=http://localhost:8080/api/user

networks:
  app-network:
    driver: bridge