swagger: '2.0'
info:
  version: '1.0'
  title: eFishery Py App
  contact: {}
host: localhost:8081
basePath: /api
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /resources:
    get:
      summary: localhost:8081/api/resources
      tags:
      - Misc
      operationId: localhost:8081/api/resources
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /resources/aggregate_price:
    get:
      summary: localhost:8081/api/resources/aggregate_price
      tags:
      - Misc
      operationId: localhost:8081/api/resources/aggregate_price
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: date
        in: query
        required: true
        type: string
        description: ''
      - name: province
        in: query
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /user:
    get:
      summary: localhost:8080/api/user
      tags:
      - Misc
      operationId: localhost:8080/api/user
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
tags:
- name: Misc
  description: ''
