heartbeat.monitors:
  - type: http
    id: auth-service
    name: Auth Service
    hosts: ["http://app:8080/health-check"]
    check.response.status: [200]
    schedule: '@every 5s'
output.elasticsearch:
  hosts: ["es01:9200"]
setup.kibana:
  host: "kib01:5601"
