metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - uptime
      - socket_summary
    enabled: true
    period: 10s
    processes: ['.*']
    cpu.metrics:  ["percentages","normalized_percentages"]
output.elasticsearch:
  hosts: ["es01:9200"]
setup.kibana:
  host: "http://kib01:5601"
